### ISSUE TITLE
NoReverseMatch exception using with models that have columns of type uuid4 as primary key

### ISSUE THREAD

**Issue by blasferna** [bartTC/django-attachments#94]
Thank you for this wonderful project. I can't find a way to use it with models that have columns of type uuid as primary key.

```
Traceback (most recent call last):
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 202, in _get_response
    response = response.render()
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/attachments/templatetags/attachments_tags.py", line 22, in attachment_form
    "form_url": add_url_for_obj(obj),
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/attachments/views.py", line 20, in add_url_for_obj
    return reverse(
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/usuario/Documentos/dev/awesome-project/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)

Exception Type: NoReverseMatch at /finances/customers/bc74f90a-5225-45c0-86ed-c70faf71453e/detail
Exception Value: Reverse for 'add' with keyword arguments '{'app_label': 'finances', 'model_name': 'customer', 'pk': UUID('bc74f90a-5225-45c0-86ed-c70faf71453e')}' not found. 1 pattern(s) tried: ['attachments/add-for/(?P<app_label>[\\w\\-]+)/(?P<model_name>[\\w\\-]+)/(?P<pk>\\d+)/$']
```

**Comment by darkpixel** [comment]
@blasferna Until a new release is cut, you can put this in your ```requirements.txt``` file:
```
git+https://github.com/darkpixel/django-attachments@GH-94-url-for-uuid4-primary-keys
```

Alternatively you can:
```
pip install git+https://github.com/darkpixel/django-attachments@GH-94-url-for-uuid4-primary-keys
```

I ran into the same issue a few minutes ago. :)

**Comment by blasferna** [comment]
Thanks a lot @darkpixel, it works!

**Comment by darkpixel** [comment]
Glad to help @blasferna!
